version: 2.1
jobs:

  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Main Tests
          command: yarn test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
